name: CI/CD - Production

on:
  push:
    branches: [master]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install frontend dependencies
        run: cd frontend && pnpm install --no-frozen-lockfile

      - name: Install backend dependencies
        run: cd backend && pnpm install --no-frozen-lockfile
